/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import javax.swing.JOptionPane;

/**
 *
 * @author 2º Info
 */
public class FormLogin extends javax.swing.JFrame {

    /**
     * Creates new form FormLogin
     */
    public FormLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entrar = new javax.swing.JLabel();
        usLogin = new javax.swing.JTextField();
        senhaLogin = new javax.swing.JPasswordField();
        btEntrar = new javax.swing.JLabel();
        Label = new javax.swing.JLabel();

        entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entrarMouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usLogin.setBorder(null);
        usLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usLoginActionPerformed(evt);
            }
        });
        getContentPane().add(usLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 90, 30));

        senhaLogin.setBorder(null);
        getContentPane().add(senhaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 80, 30));

        btEntrar.setText("  ");
        btEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btEntrarMouseClicked(evt);
            }
        });
        getContentPane().add(btEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 356, 140, 30));

        Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/2.png"))); // NOI18N
        getContentPane().add(Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void entrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrarMouseClicked
        // TODO add your handling code here:
        new FormTelaInic().setVisible(true);
    }//GEN-LAST:event_entrarMouseClicked

    private void usLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usLoginActionPerformed

    private void btEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btEntrarMouseClicked
        // TODO add your handling code here:
        String usuario = "Daniele";
        String senha = "Dani123";
        String u = usLogin.getText();
        String s = senhaLogin.getText();
       
        if((usuario.equalsIgnoreCase(u)) && (senha.equalsIgnoreCase(s))){
            new FormTelaMenu().setVisible(true);
            dispose();
        }else if ((u.equals("")) && (s.equals(""))){
            JOptionPane.showMessageDialog(null, "Parece que você esqueceu de digitar seus dados!");
        } else{
            JOptionPane.showMessageDialog(null, "Algo está errado. Tente novamente!");
        }
    }//GEN-LAST:event_btEntrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label;
    private javax.swing.JLabel btEntrar;
    private javax.swing.JLabel entrar;
    private javax.swing.JPasswordField senhaLogin;
    private javax.swing.JTextField usLogin;
    // End of variables declaration//GEN-END:variables
}
