/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author 2º Info
 */
public class FormMenuRec extends javax.swing.JFrame {

    /**
     * Creates new form FormMenuRec
     */
    public FormMenuRec() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        voltar = new javax.swing.JLabel();
        Acao = new javax.swing.JLabel();
        Romance = new javax.swing.JLabel();
        Fantasia = new javax.swing.JLabel();
        FicCien = new javax.swing.JLabel();
        Terror = new javax.swing.JLabel();
        Suspense = new javax.swing.JLabel();
        menuRec = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voltarMouseClicked(evt);
            }
        });
        getContentPane().add(voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 80, 30));

        Acao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AcaoMouseClicked(evt);
            }
        });
        getContentPane().add(Acao, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 80, 70));

        Romance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RomanceMouseClicked(evt);
            }
        });
        getContentPane().add(Romance, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 80, 70));

        Fantasia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FantasiaMouseClicked(evt);
            }
        });
        getContentPane().add(Fantasia, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 90, 60));

        FicCien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FicCienMouseClicked(evt);
            }
        });
        getContentPane().add(FicCien, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 90, 60));

        Terror.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TerrorMouseClicked(evt);
            }
        });
        getContentPane().add(Terror, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 80, 60));

        Suspense.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SuspenseMouseClicked(evt);
            }
        });
        getContentPane().add(Suspense, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 80, 60));

        menuRec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/4.png"))); // NOI18N
        menuRec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuRecMouseClicked(evt);
            }
        });
        getContentPane().add(menuRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void voltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarMouseClicked
        // TODO add your handling code here:
        new FormTelaMenu().setVisible(true);
    }//GEN-LAST:event_voltarMouseClicked

    private void AcaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcaoMouseClicked
        // TODO add your handling code here:
        new FormRecAcao().setVisible(true);
    }//GEN-LAST:event_AcaoMouseClicked

    private void RomanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RomanceMouseClicked
        // TODO add your handling code here:
        new FormRecRom().setVisible(true);
    }//GEN-LAST:event_RomanceMouseClicked

    private void FantasiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FantasiaMouseClicked
        // TODO add your handling code here:
        new FormRecFant().setVisible(true);
    }//GEN-LAST:event_FantasiaMouseClicked

    private void FicCienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FicCienMouseClicked
        // TODO add your handling code here:
        new FormRecFic().setVisible(true);
    }//GEN-LAST:event_FicCienMouseClicked

    private void menuRecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuRecMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuRecMouseClicked

    private void SuspenseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SuspenseMouseClicked
        // TODO add your handling code here:
        new FormRecSusp().setVisible(true);
    }//GEN-LAST:event_SuspenseMouseClicked

    private void TerrorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TerrorMouseClicked
        // TODO add your handling code here:
        new FormRecTerror().setVisible(true);
    }//GEN-LAST:event_TerrorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenuRec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenuRec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenuRec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenuRec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenuRec().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Acao;
    private javax.swing.JLabel Fantasia;
    private javax.swing.JLabel FicCien;
    private javax.swing.JLabel Romance;
    private javax.swing.JLabel Suspense;
    private javax.swing.JLabel Terror;
    private javax.swing.JLabel menuRec;
    private javax.swing.JLabel voltar;
    // End of variables declaration//GEN-END:variables
}
